# AdminTool by Michael1011
# Version 1.1.0

JoinMessages:
  EnableWelcomePlayer: true
# Activates "Welcome <player>!" message on join.

  SecondLine: "&6Updates: &emade all messages editable!"
  ThirdLine: "&6Coming updates: &emaintenance mode..."
# Changes the join messages of non admins. Write nothing between the quotation marks to disable it.

Settings: 
  OPPrefixEnable: true
# Should Admins have a prefix in the tablist and the chat?

  OPPrefix: "&4[Admin] "
# This appears in front of the name of a admin in the chat.
  
  OPColor: "§4"
# Sorry, but you have to set a § (not a &) in front of the color code. :/

  GMARadius: 500
# radius of the /gma command

  CustomSpawn: false
# Set nothing here! Its automatically true when you set the spawn with /spawn set .

  spawnCoord: false
# The coords of the spawn. Set it with /spawn set .

Homes:
# Here appears something when a player sets his home with /home set.