main: main.main
name: AdminTool
version: 1.3.7
description: Admin Tool by Michael1011
author: Michael1011
database: false

commands:
   gm:
     description: "easy switch between gamemode 1 and 0"
     aliases: [game, gamem]
     usage: /gm [0, 1]
   invsee:
     description: "see the inventory of an other player"
     aliases: [invs]
     usage: /invsee <player>
   day:
     description: "set the time in your world to day"
     aliases: [d]
     usage: /day
   adminreload:
     description: "reload the config"
     aliases: [ar, adminr, areload]
     usage: /lebenreload
   gma:
     description: "sets all players in a specific radius in gamemode 1 or 0"
     aliases: [gms, gmk]
     usage: /gma [0, 1]
   spawn:
     description: "teleport yourself to the spawn"
     aliases: [sp]
     usage: /spawn [set]
   home:
     description: "teleport yourself to your home"
     aliases: [ho]
     usage: /home [set]
   maintenance:
     description: "enable/disable the maintenance mode"
     aliases: [maint]
     usage: /maintenance [on, off]
   warp:
     description: "teleport yourself to the warp with /warp <name>"
     aliases: [wp]
     usage: /warp <name>
   admingui:
     description: "open the admin gui"
     usage: /admingui <argument>
   clearchat:
     description: "clear the chat"
     aliases: [cc, clearc]
     usage: /clearchat <argument>
   ping:
     description: "get your ping"
     usage: /ping <player>
   mute:
     description: "mute a player"
     usage: /mute <player>
   globalmute:
     description: "disable the chat"
     aliases: [gmute, globalm]
     usage: /globalmute <on, off>
     
permissions:
   admintool.*:
        description: "all permissions of the plugin"
        children:
            admintool.reload: true
            admintool.day: true
            admintool.spawn: true
            admintool.spawn.set: true
            admintool.home: true
            admintool.home.multiple: true
            admintool.invsee: true
            admintool.gm: true
            admintool.gma: true
            admintool.NameTag: true
            admintool.joinMessage: true
            admintool.maintenance.set: true
            admintool.maintenance.join: true
            admintool.warp.create: true
            admintool.warp.*: true
            admintool.gui: true
            admintool.clearchat: true
            admintool.clearchat.global: true
            admintool.ping: true
            admintool.ping.others: true
            admintool.mute: true
            admintool.globalmute: true
            admintool.globalmute.chat: true
   admintool.reload:
        description: "for the /adminreload command"
        default: op
   admintool.day:
        description: "for the /day command"
        default: op
   admintool.spawn:
        description: "for the /spawn command"
        default: true
   admintool.spawn.set:
        description: "for the /spawn set command"
        default: op
   admintool.home:
        description: "for the commands /home and /home set"
        default: true
   admintool.home.multiple:
        description: "allows people to have multiple homes"
        default: op
   admintool.invsee:
        description: "for the /invsee commad"
        default: op
   admintool.gm:
        description: "for the /gm command"
        default: op
   admintool.gma:
        description: "for the /gma command"
        default: op
   admintool.NameTag:
        description: "for the name tags in the tablist and in the chat"
        default: op
   admintool.joinMessage:
        description: "for the admin join messages and the update notification"
        default: op
   admintool.maintenance.set:
        description: "to toggle the maintenance mode (/maintenance)"
        default: op
   admintool.maintenance.join:
        description: "join when the maintenance mode is on"
        default: op
   admintool.warp.create:
        description: "create warps (/warp create <warp name>)"
        default: op
   admintool.warp.*:
        description: "to teleport yourself to the warps"
        default: true
   admintool.gui:
        description: "permission to open the gui"
        default: op
   admintool.clearchat.global:
        description: "to clear the chat of all"
        default: op
   admintool.clearchat:
        description: "clear your chat"
        default: true
   admintool.ping:
        description: "see your ping /ping"
        default: true
   admintool.ping.others:
        description: "see of other players"
        default: op
   admintool.mute:
        description: "mute players"
        default: op
   admintool.globalmute:
        description: "toggle the global mute"
        default: op
   admintool.globalmute.chat:
        description: "chat when the globalmute is active"
        default: op